name: EnderCompass
main: me.Fahlur.EnderCompass.EnderCompassPlugin
version: 1.3.0
author: Fahlur
description: Teleportation Compass
depend: [WorldGuard]
commands:
  endercompass:
      description: Main command returns version
      aliases: []
      usage: /<command>
permissions:
   ctp.jumpto:
    description: Teleports player to location they are aiming at
   ctp.jumpto.nether:
    description: Teleports players around in the Nether
   ctp.jumpto.end:
    description: Teleports players around in the The End